wOBA relativo a Outs
andres-alvarado/beisbol-analitica pull request #133
Opened 2021-03-21 05:42 UTC by andres-alvarado

2021-03-23 07:29 UTC, IvanVC21 requested changes
1. Sugeriría remover el `RelativeToOuts` en la definicion final de wOBA, pues esta métrica es inherentemente relativa a los outs y por ende inventarle otro nombre al primer wOBA (al que le falta la sumatoria del run value de los outs).
2. No se si sea necesario el agregar el wOBA de la liga y la escala de wOBA en la tabla de agg_batting_stats. En dado caso que sea no necesario para que no marque error, sugeriría removerlos.

2021-03-23 22:58 UTC, andres-alvarado commented
> 1. Sugeriría remover el `RelativeToOuts` en la definicion final de wOBA, pues esta métrica es inherentemente relativa a los outs y por ende inventarle otro nombre al primer wOBA (al que le falta la sumatoria del run value de los outs).

Entiendo lo que dices y concuerdo hasta cierto punto. En mi opinion las dos cosas son diferentes. El wOBA puro(sin outs ) es el woba original. wOBARelativeToOuts es wOBA pero a una escala diferente. Acepto sugerencias al nombre, pero creo no nos hace daño tener ambas.  Estoy de acuerdo tambien que el tener ambas puede causar alguna confusion.

> 2. No se si sea necesario el agregar el wOBA de la liga y la escala de wOBA en la tabla de agg_batting_stats. En dado caso que sea no necesario para que no marque error, sugeriría removerlos.

La ventaja de tener todos los datos en una sola tabla es que facilita hacer "debugging" y encontrar errores en los calculos. Ademas, si no los guardaramos aqui tendriamos que hacer mas tablas para estos datos. Eso causaria mas problemas a futuro.

2021-03-24 02:53 UTC, IvanVC21 commented
>  El wOBA puro(sin outs ) es el woba original. wOBARelativeToOuts es wOBA pero a una escala diferente. Acepto sugerencias al nombre, pero creo no nos hace daño tener ambas. Estoy de acuerdo tambien que el tener ambas puede causar alguna confusion.

Claro, podríamos tener los dos. Pero si estamos realizando este proyecto con el fin de meterlo a producción (potencialmente a un sitio web) creo que lo mejor seria hacerlo lo mas amigable posible para el usuario, de ahi mi sugerencia para que el wOBARelativeToOuts sea renombrado a _wOBA_, pues esta es la version final que un usuario buscaria.

2021-03-24 05:11 UTC, andres-alvarado commented
Cierto. Es verdad lo que dices. El re nombramiento lo podemos hacer a nivel página de web.

2021-03-24 18:51 UTC, IvanVC21 approved these changes

2021-03-24 18:51 UTC, merged