park factors para distintas metricas
andres-alvarado/beisbol-analitica pull request #135
Opened 2021-04-06 03:10 UTC by andres-alvarado

Agregando hits, singls, doubles, triples y homeRuns

2021-04-07 18:20 UTC, IvanVC21 requested changes
Creo que valdria la pena agregar park factor para ponches y bases por bola.

2021-04-08 02:07 UTC, andres-alvarado commented
Ivan tienes toda la razon, debemos meter aun mas metricas. Dejemoslas para un futuro.

2021-04-08 04:17 UTC, IvanVC21 commented
closes #117

2021-04-08 04:18 UTC, IvanVC21 approved these changes

2021-04-08 04:18 UTC, merged