Agg Pitching Stats
andres-alvarado/beisbol-analitica pull request #81
Opened 2021-01-27 03:23 UTC by andres-alvarado

Agregando Pitching Stats. Este nuevo enfoque utiliza un update en vez de calcular las estadisticas en el query dinamico.

2021-01-29 08:25 UTC, IvanVC21 commented
Unicamente por el momento añadiria: `savePercentage = IF (saveOpportunities > 0, saves / saveOpportunities, NULL)` 
y `winPercentage = IF (wins > 0, wins / (wins + losses, NULL)`
De ahi en fuera todo excelente.

2021-01-29 08:32 UTC, IvanVC21 requested changes
Unicamente por el momento añadiria: `savePercentage = IF (saveOpportunities > 0, saves / saveOpportunities, NULL)`
y `winPercentage = IF (wins > 0, wins / (wins + losses, NULL)`

2021-01-30 03:50 UTC, andres-alvarado commented
Tienes razon, debemos incluir winPercentage. Trabajare en esto el fin de semana.

2021-02-01 02:53 UTC, IvanVC21 commented
Excelente, muchas gracias @andres-alvarado !

2021-02-01 02:54 UTC, IvanVC21 approved these changes

2021-02-01 02:57 UTC, merged